from celery import shared_task


@shared_task
def send_daily_sales_report():
    """Generate and email daily sales summary to owner."""
    from django.core.mail import send_mail
    from django.conf import settings
    from django.utils import timezone
    from django.db.models import Sum, Count
    from apps.pos.models import Sale

    today = timezone.localdate()
    sales = Sale.objects.filter(created_at__date=today, status='completed')
    agg = sales.aggregate(total=Sum('total_amount'), count=Count('id'))

    body = (
        f"Daily Sales Report — {today}\n\n"
        f"Total Revenue: Rs.{agg['total'] or 0}\n"
        f"Total Transactions: {agg['count'] or 0}\n\n"
        f"Generated by pos.orangelogs.com"
    )
    send_mail(
        subject=f'[Saloon] Daily Report — {today}',
        message=body,
        from_email=settings.DEFAULT_FROM_EMAIL,
        recipient_list=[settings.DEFAULT_FROM_EMAIL],
    )
    return f'Daily report sent for {today}'
